name: Python FastAPI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  FIREBASE_SERVICE_ACCOUNT_KEY: '{"type": "service_account","project_id": "attendance-tracker-42933","private_key_id": "d67dc953c5dcf7f0ff43fbe0250cd1c91e24ff51","private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDERd7fLnyjZla2\n28YfLPeYWN7yCOIbFYSdKtHM0wIdfQH7jzvi4ELbWuJ3Vgr4xDZqxsr6mpQBom4M\nnI34Wf+Vf4VrTc/osu6fglUVEg/DcKkWCoXNvSPc/BmOkUfuig9kAKXH16Ff3amS\nfBjyD6YjXFYpMYW7K6dNN+SNQAA0yMK17d6UMmyUNQK78Ty45pxDphrmDguzon2N\nn7VVMguc+/kiQXcgxFH+I8qchQroymae0qUSets2EFiq3ZIRok/x1PmUQpyNfgVO\ng2MCGiZIrwoqq3qS8JpFEB2XvSSCmJ9jV7o4UkNl/R5LxSO8dZuxUBxhYol/NLkp\nmpNVnskbAgMBAAECggEAEJvgXB7ZHD4E7iy94MB+OUL3/B+lUT5qaPRefvMyNXWb\nzS0Al9Z7bIg4gXm4rEwfq2ckIRMjSC91xD/Glx1ijpo/xjtLnI5GZB10KWLMY7EC\na047pr6FLOZGcV/jkuYq9D7xHcP7sMWXW8Eq8+eVcF5CykdEYPjfi54ZtfGUXY2j\njp7JVoyJdPsYCelJ0hbXDF7mObz0R+XqmXFb2tjEK5mycTUAHzmQW6LJqMHpcn1N\nOM3taqRD7rI5sl4pddX/BEIxZTrrD+Nuk82DjyJPnhfzs3pCzqmkK6H+OkisC0tN\nG4TDr9j8AtFOU3GyBLoExXLpgon0coZ4g1gB3EDETQKBgQDyAyOedbFT/yvKkp8I\nJBsNUSxj1ba2wUAjBfIZkK1L4AKscSPdDTEXXuCAohrQnjnqr6hY7LDciAJ8+Nij\n3L9cw4rR6zuGpP9GG1z8tFQaX1rcAfooAAbISenPRsD3tgklWAmruU61x/44kOqh\n9usfKodaH6Npx6svQfHKOmSWDwKBgQDPnfae3yt1tfJA5KwxXQKXUMy7Fr/K9Lqy\nomRMkcBhVnzVL580xh/G7SEdyuOfANWJ4Knx5HSYDv3/y+gWg0MIX0uIWvKXkzad\nUoUNDYQgAOQE4wPEmDN+K9OJ0/Csa3fok6eFqaiVopzOibbjTibu4D43gelkdX4e\nrJ5lzXDINQKBgFqBfAedohR0oC7gyGKmBgvj6ILpgKw190NhzNlstrJicv2ETlIz\nxcEktTbF6NtN4QD4ci/XTIkcwDl2YqZdPp91bWv12cwP1nukbhD/a1h1gqg2gRQG\ndoLeyXa/0hiRVjhGBU/YPCxVP6ht4aFykxmTsQyuOlGr30QMGF11mvpXAoGAPP4F\n9pRPWyxRd9j18SaG3VciXhAH1iLhOhtU5d2nq7DRyXtNBR7zNOhy4yK4jfybvv6e\nTm60BfvZiK0piHuVVL9SHEPDot3fnIYiijwfRZudYQYkFDw2XGmZopL90FleB5hh\nDXZTDWqRMGfqr4pFC8Ya4QmsPBP8Mhy6B+Q7rsUCgYBJLGgSYZ9xxS7gsQqxrtK0\noaMkVGz/NvZo08wOzZ6pYDLMG9H3TCb+X8Vib+G5hzDWNQueowA2dsOOCrq5tQRM\nRW0VPktyt8PY0zLvvuaK8+b1eUMMIVrASA7HqZlCxTHGCUpKdc3DlvG0yZtN4Y/x\nSItdnnSp+1uKuXfyt0LYJg==\n-----END PRIVATE KEY-----\n","client_email": "firebase-adminsdk-iz8eg@attendance-tracker-42933.iam.gserviceaccount.com","client_id": "103829095734799918036","auth_uri": "https://accounts.google.com/o/oauth2/auth","token_uri": "https://oauth2.googleapis.com/token","auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-iz8eg%40attendance-tracker-42933.iam.gserviceaccount.com","universe_domain": "googleapis.com"}'
  FIREBASE_CONFIG: '{"apiKey": "AIzaSyBB4A1kUpk93rG1uZ66EAVZRSdGix2AmBc","authDomain": "attendance-tracker-42933.firebaseapp.com","databaseURL": "https://attendance-tracker-42933-default-rtdb.europe-west1.firebasedatabase.app","projectId": "attendance-tracker-42933","storageBucket": "attendance-tracker-42933.appspot.com","messagingSenderId": "435935764927","appId": "1:435935764927:web:4ae57c9c5dbd48f58bc10a","measurementId": "G-V1RC5TWBX6"}'
  STRIPE_SK: 'sk_test_51P4K6RP5W2QTAm7Z3PCGtFtjPbG90LhJC8Oc5adIhpUHwX5jKI10QSrEAjj8hmySoLFU1RJE54CPkV47P84skffo0031H2TSCC'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Debug environment variables
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT_KEY
        echo $FIREBASE_CONFIG
        echo $STRIPE_SK
    - name: Test with pytest
      run: |
        pytest
